import Head from "next/head";
import dynamic from "next/dynamic";
import Home from "../src/screens/Home"
// @ts-ignore
const Sidebar = dynamic(() => import("components/sidebar"), {
  suspense: true,
});

export default function HomeScreen() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
    </>
  );
}
